---
new_page_extension: md
auto_deploy: false
admin_path: public/admin
webhook_url:
sections:
- type: heading
  label: Content
- type: directory
  path: posts
  label: Blog Posts
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: videos
  label: Videos
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: Config
- type: document
  path: data/config.json
  label: Site Info
upload_dir: public
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".next"
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry-preview
